# Generated by Django 5.2.4 on 2025-07-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="approveddoctor",
            old_name="name",
            new_name="full_name",
        ),
        migrations.AlterField(
            model_name="approveddoctor",
            name="doctor_id",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
